# Generated by Django 4.2.4 on 2023-08-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="شماره تلفن"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("address", models.TextField(verbose_name="آدرس")),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام محصول")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                ("available", models.BooleanField(default=True, verbose_name="موجود")),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="شماره تلفن"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("skills", models.TextField(verbose_name="مهارت\u200cها")),
            ],
            options={
                "verbose_name": "تکنسین",
                "verbose_name_plural": "تکنسین\u200cها",
            },
        ),
    ]
