# Generated by Django 4.2.4 on 2023-08-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="region",
            field=models.SmallIntegerField(default=0, verbose_name="منطقه"),
        ),
        migrations.AddField(
            model_name="technician",
            name="region",
            field=models.SmallIntegerField(default=0, verbose_name="منطقه سکونت"),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_requested", models.DateField(verbose_name="تاریخ درخواست")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.technician",
                        verbose_name="تکنسین",
                    ),
                ),
            ],
            options={
                "verbose_name": "سرویس",
                "verbose_name_plural": "سرویس\u200cها",
            },
        ),
    ]
