# Generated by Django 4.2.4 on 2023-11-29 07:02

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_call_product_alter_call_date_alter_call_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="backup_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره تلفن پشتیبان"
            ),
        ),
        migrations.AlterField(
            model_name="notsoldproduct",
            name="date_of_call",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 7, 2, 49, 436782, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ تماس",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 7, 2, 49, 436782, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ و زمان تعیین شده",
            ),
        ),
        migrations.AlterField(
            model_name="soldproduct",
            name="date_of_sell",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 7, 2, 49, 436782, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ فروش",
            ),
        ),
    ]
