# Generated by Django 4.2.4 on 2023-08-28 12:21

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_customer_region_technician_region_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="date_requested",
            field=django_jalali.db.models.jDateTimeField(verbose_name="تاریخ درخواست"),
        ),
    ]
