# Generated by Django 4.2.4 on 2023-11-29 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_call_operator_alter_notsoldproduct_date_of_call_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="operator",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="اپراتور مسئول"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="notsoldproduct",
            name="date_of_call",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 8, 11, 20, 735284, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ تماس",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 8, 11, 20, 735284, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ و زمان تعیین شده",
            ),
        ),
        migrations.AlterField(
            model_name="soldproduct",
            name="date_of_sell",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 8, 11, 20, 735284, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ فروش",
            ),
        ),
    ]
