# Generated by Django 4.2.4 on 2023-08-28 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_service_date_requested"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    django_jalali.db.models.jDateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ تماس"
                    ),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="پاسخ داده شده؟"),
                ),
                (
                    "respond",
                    models.CharField(
                        choices=[
                            ("positive", "مثبت"),
                            ("neutral", "خنثی"),
                            ("negative", "منفی"),
                        ],
                        max_length=50,
                        verbose_name="پاسخ",
                    ),
                ),
                ("details", models.TextField(verbose_name="جزئیات")),
            ],
            options={
                "verbose_name": "تماس",
                "verbose_name_plural": "تماس\u200cها",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="region",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="service",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="service",
            name="date_requested",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="email",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="skills",
        ),
        migrations.AddField(
            model_name="customer",
            name="backup_number",
            field=models.CharField(
                max_length=20, null=True, verbose_name="شماره تلفن پشتیبان"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="details",
            field=models.TextField(null=True, verbose_name="جزئیات"),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(
                default=-1, max_length=10, verbose_name="شماره شناسنامه"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="number",
            field=models.CharField(
                default=-1, max_length=20, verbose_name="شماره تلفن"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="region_number",
            field=models.IntegerField(default=-1, verbose_name="شماره منطقه"),
        ),
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.TextField(null=True, verbose_name="جزئیات"),
        ),
        migrations.AddField(
            model_name="product",
            name="filter1",
            field=models.SmallIntegerField(default=-1, verbose_name="فیلتر 1"),
        ),
        migrations.AddField(
            model_name="product",
            name="filter2",
            field=models.SmallIntegerField(default=-1, verbose_name="فیلتر 2"),
        ),
        migrations.AddField(
            model_name="product",
            name="filter3",
            field=models.SmallIntegerField(default=-1, verbose_name="فیلتر 3"),
        ),
        migrations.AddField(
            model_name="product",
            name="filter4",
            field=models.SmallIntegerField(default=-1, verbose_name="فیلتر 4"),
        ),
        migrations.AddField(
            model_name="product",
            name="filter5",
            field=models.SmallIntegerField(default=-1, verbose_name="فیلتر 5"),
        ),
        migrations.AddField(
            model_name="product",
            name="filter6",
            field=models.SmallIntegerField(default=-1, verbose_name="فیلتر 6"),
        ),
        migrations.AddField(
            model_name="product",
            name="model_number",
            field=models.CharField(default=-1, max_length=50, verbose_name="شماره مدل"),
        ),
        migrations.AddField(
            model_name="service",
            name="details",
            field=models.TextField(null=True, verbose_name="جزئیات"),
        ),
        migrations.AddField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ و زمان تعیین شده"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_done",
            field=models.BooleanField(default=False, verbose_name="انجام شده؟"),
        ),
        migrations.AddField(
            model_name="service",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.product",
                verbose_name="محصول مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="details",
            field=models.TextField(null=True, verbose_name="جزئیات"),
        ),
        migrations.AlterField(
            model_name="service",
            name="technician",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.technician",
                verbose_name="تکنسین",
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="region",
            field=models.IntegerField(
                default=-1, verbose_name="منطقه\u200cی محل زندگی"
            ),
        ),
        migrations.CreateModel(
            name="SoldProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_sell",
                    django_jalali.db.models.jDateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ فروش"
                    ),
                ),
                ("details", models.TextField(null=True, verbose_name="جزئیات")),
                (
                    "calls",
                    models.ManyToManyField(
                        blank=True, to="dashboard.call", verbose_name="تماس\u200cها"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول فروخته شده",
                "verbose_name_plural": "محصولات فروخته شده",
            },
        ),
        migrations.AddField(
            model_name="call",
            name="service",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.service",
                verbose_name="سرویس مرتبط",
            ),
        ),
    ]
