# Generated by Django 4.2.4 on 2023-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_call_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالیت کارکنان",
                "verbose_name_plural": "فعالیت\u200cهای کارکنان",
            },
        ),
    ]
