# Generated by Django 4.2.4 on 2023-08-29 01:38

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_logmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="recall_date",
            field=django_jalali.db.models.jDateField(
                null=True, verbose_name="تاریخ تماس دوباره"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="home_number",
            field=models.CharField(
                default=-1, max_length=20, verbose_name="شماره تلفن"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="date",
            field=django_jalali.db.models.jDateField(
                default=datetime.date(2023, 8, 29), verbose_name="تاریخ تماس"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="respond",
            field=models.CharField(
                choices=[
                    ("set_time", "تعیین زمان صورت گرفته است."),
                    ("recall", "یادآوری دوباره شود"),
                    ("self", "خودم تعویض می\u200cکنم"),
                ],
                max_length=50,
                verbose_name="پاسخ",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id_number",
            field=models.CharField(default=-1, max_length=10, verbose_name="اشتراک"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="number",
            field=models.CharField(
                default=-1, max_length=20, verbose_name="شماره موبایل"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="filter1",
            field=models.SmallIntegerField(
                default=-1, verbose_name="فیلتر 1 - دوره تعویض"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="filter2",
            field=models.SmallIntegerField(
                default=-1, verbose_name="فیلتر 2 - دوره تعویض"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="filter3",
            field=models.SmallIntegerField(
                default=-1, verbose_name="فیلتر 3 - دوره تعویض"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="filter4",
            field=models.SmallIntegerField(
                default=-1, verbose_name="فیلتر 4 - دوره تعویض"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="filter5",
            field=models.SmallIntegerField(
                default=-1, verbose_name="فیلتر 5 - دوره تعویض"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="filter6",
            field=models.SmallIntegerField(
                default=-1, verbose_name="فیلتر 6 - دوره تعویض"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 8, 29, 1, 38, 15, 898343, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ و زمان تعیین شده",
            ),
        ),
        migrations.AlterField(
            model_name="soldproduct",
            name="date_of_sell",
            field=django_jalali.db.models.jDateField(
                default=datetime.date(2023, 8, 29), verbose_name="تاریخ فروش"
            ),
        ),
    ]
