# Generated by Django 4.2.4 on 2023-08-29 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_remove_call_recall_date_service_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 8, 29, 8, 7, 14, 546017, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ و زمان تعیین شده",
            ),
        ),
    ]
