# Generated by Django 4.2.4 on 2023-11-19 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_alter_call_date_alter_service_due_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="date",
            field=django_jalali.db.models.jDateField(
                default=datetime.date(2023, 11, 19), verbose_name="تاریخ تماس"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 17, 12, 657438, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ و زمان تعیین شده",
            ),
        ),
        migrations.AlterField(
            model_name="soldproduct",
            name="date_of_sell",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 17, 12, 657438, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ فروش",
            ),
        ),
        migrations.CreateModel(
            name="NotSoldProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_call",
                    django_jalali.db.models.jDateTimeField(
                        default=datetime.datetime(
                            2023,
                            11,
                            19,
                            7,
                            17,
                            12,
                            657438,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="تاریخ تماس",
                    ),
                ),
                ("details", models.TextField(null=True, verbose_name="جزئیات")),
                (
                    "calls",
                    models.ManyToManyField(
                        blank=True, to="dashboard.call", verbose_name="تماس\u200cها"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول تعویق فروش",
                "verbose_name_plural": "محصولات تعویق فروش",
            },
        ),
    ]
