# Generated by Django 4.2.4 on 2023-11-19 07:44

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_alter_call_date_alter_service_due_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="attitude",
            field=models.TextField(
                blank=True, null=True, verbose_name="ویژگی\u200cهای شخصیتی"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="notsoldproduct",
            name="date_of_call",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 44, 8, 679229, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ تماس",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 44, 8, 679229, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ و زمان تعیین شده",
            ),
        ),
        migrations.AlterField(
            model_name="soldproduct",
            name="date_of_sell",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 44, 8, 679229, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ فروش",
            ),
        ),
    ]
