# Generated by Django 4.2.4 on 2023-11-19 07:44

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_customer_attitude_product_model_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notsoldproduct",
            name="date_of_call",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 44, 41, 647525, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ تماس",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date_time",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 44, 41, 647525, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ و زمان تعیین شده",
            ),
        ),
        migrations.AlterField(
            model_name="soldproduct",
            name="date_of_sell",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 7, 44, 41, 647525, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ فروش",
            ),
        ),
    ]
